run:
  timeout: 5m
  skip-dirs-use-default: true
  modules-download-mode: mod
linters:
  enable:
    #linters maintained by golang.org
    - gofmt
    - goimports
    - revive
    - govet
    #linters default enabled by golangci-lint .
    - deadcode
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    #other linters supported by golangci-lint.
    - gocyclo
    - whitespace
    - dupl
    - gosec
  linters-settings:
    goimports:
      local-prefixes: github.com/cloud-native/elasticweb
    gocyclo:
      #minimal cyclomatic complexity to report
      min-complexity: 20
    dupl:
      threshold: 300